# Generated by Django 4.1.7 on 2023-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
