# Generated by Django 4.1.7 on 2023-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_booksmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
